-- ==============================================================================
-- QuinutDB Seed Data for Supabase
-- Run this in the Supabase SQL Editor after running schema.sql
-- ==============================================================================

insert into public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, official_url, download_url, github_repo
) values (
  'daijisho',
  'frontend',
  'Daijishō',
  'A retro launcher that manages your retro games libraries with built-in scraping, extensive theme support, and launcher replacement capability.',
  'Free & Open Source',
  'Active',
  ARRAY['Android'],
  true,
  'Rich',
  true,
  true,
  true,
  5,
  4,
  4,
  'https://avatars.githubusercontent.com/u/130823084?v=4',
  'https://opengraph.githubassets.com/1/TapiocaFox/Daijishou',
  'https://github.com/TapiocaFox/Daijishou',
  'https://play.google.com/store/apps/details?id=com.tapiocafox.daijishou',
  'TapiocaFox/Daijishou'
) on conflict (id) do update set
  name = excluded.name,
  short_desc = excluded.short_desc,
  pricing = excluded.pricing,
  status = excluded.status,
  supported_platforms = excluded.supported_platforms,
  has_built_in_scraper = excluded.has_built_in_scraper,
  theme_support = excluded.theme_support,
  touch_optimized = excluded.touch_optimized,
  gamepad_optimized = excluded.gamepad_optimized,
  can_replace_home_launcher = excluded.can_replace_home_launcher,
  baseline_adoption = excluded.baseline_adoption,
  baseline_ease_of_use = excluded.baseline_ease_of_use,
  baseline_activity = excluded.baseline_activity,
  logo_url = excluded.logo_url,
  cover_image_url = excluded.cover_image_url,
  official_url = excluded.official_url,
  download_url = excluded.download_url,
  github_repo = excluded.github_repo,
  updated_at = timezone('utc'::text, now());

insert into public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, official_url, download_url, github_repo
) values (
  'es-de',
  'frontend',
  'ES-DE',
  'The definitive frontend for browsing and launching games from your multi-platform collection with unrivaled theme customization.',
  'Free & Open Source',
  'Active',
  ARRAY['Android', 'Linux', 'Windows', 'macOS'],
  true,
  'Rich',
  false,
  true,
  false,
  5,
  3,
  5,
  'https://gitlab.com/uploads/-/system/project/avatar/18817634/emulationstation_1024x1024.png?v=1789307732',
  'https://gitlab.com/uploads/-/system/project/avatar/18817634/emulationstation_1024x1024.png?v=1789307732',
  'https://es-de.org/',
  'https://gitlab.com/es-de/emulationstation-de/-/releases',
  null
) on conflict (id) do update set
  name = excluded.name,
  short_desc = excluded.short_desc,
  pricing = excluded.pricing,
  status = excluded.status,
  supported_platforms = excluded.supported_platforms,
  has_built_in_scraper = excluded.has_built_in_scraper,
  theme_support = excluded.theme_support,
  touch_optimized = excluded.touch_optimized,
  gamepad_optimized = excluded.gamepad_optimized,
  can_replace_home_launcher = excluded.can_replace_home_launcher,
  baseline_adoption = excluded.baseline_adoption,
  baseline_ease_of_use = excluded.baseline_ease_of_use,
  baseline_activity = excluded.baseline_activity,
  logo_url = excluded.logo_url,
  cover_image_url = excluded.cover_image_url,
  official_url = excluded.official_url,
  download_url = excluded.download_url,
  github_repo = excluded.github_repo,
  updated_at = timezone('utc'::text, now());

insert into public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, official_url, download_url, github_repo
) values (
  'delta',
  'frontend',
  'Delta',
  'The premier classic games frontend and emulator on the Apple App Store, supporting NES, SNES, N64, GBC, GBA, and DS with controller skins and boxart scraping.',
  'Free & Open Source',
  'Active',
  ARRAY['iOS', 'iPadOS'],
  true,
  'Rich',
  true,
  true,
  false,
  5,
  5,
  4,
  'https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/ed/08/91/ed089193-2334-fd9b-752e-fc330791ee48/AppIcon-0-0-1x_U007epad-0-0-0-1-0-0-sRGB-85-220.png/512x512bb.jpg',
  'https://opengraph.githubassets.com/1/rileytestut/Delta',
  'https://deltaemulator.com/',
  'https://apps.apple.com/us/app/delta-game-emulator/id1048524688',
  'rileytestut/Delta'
) on conflict (id) do update set
  name = excluded.name,
  short_desc = excluded.short_desc,
  pricing = excluded.pricing,
  status = excluded.status,
  supported_platforms = excluded.supported_platforms,
  has_built_in_scraper = excluded.has_built_in_scraper,
  theme_support = excluded.theme_support,
  touch_optimized = excluded.touch_optimized,
  gamepad_optimized = excluded.gamepad_optimized,
  can_replace_home_launcher = excluded.can_replace_home_launcher,
  baseline_adoption = excluded.baseline_adoption,
  baseline_ease_of_use = excluded.baseline_ease_of_use,
  baseline_activity = excluded.baseline_activity,
  logo_url = excluded.logo_url,
  cover_image_url = excluded.cover_image_url,
  official_url = excluded.official_url,
  download_url = excluded.download_url,
  github_repo = excluded.github_repo,
  updated_at = timezone('utc'::text, now());

insert into public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, official_url, download_url, github_repo
) values (
  'retroarch',
  'frontend',
  'RetroArch',
  'The foundational open-source multi-system frontend and modular engine, powering emulation, shaders, netplay, and game libraries on both App Store and Play Store.',
  'Free & Open Source',
  'Active',
  ARRAY['Android', 'iOS', 'Windows', 'Linux', 'macOS', 'tvOS'],
  true,
  'Rich',
  true,
  true,
  false,
  5,
  2,
  5,
  'https://avatars.githubusercontent.com/u/7994464?v=4',
  'https://opengraph.githubassets.com/1/libretro/RetroArch',
  'https://www.retroarch.com/',
  'https://apps.apple.com/us/app/retroarch/id6499539433',
  'libretro/RetroArch'
) on conflict (id) do update set
  name = excluded.name,
  short_desc = excluded.short_desc,
  pricing = excluded.pricing,
  status = excluded.status,
  supported_platforms = excluded.supported_platforms,
  has_built_in_scraper = excluded.has_built_in_scraper,
  theme_support = excluded.theme_support,
  touch_optimized = excluded.touch_optimized,
  gamepad_optimized = excluded.gamepad_optimized,
  can_replace_home_launcher = excluded.can_replace_home_launcher,
  baseline_adoption = excluded.baseline_adoption,
  baseline_ease_of_use = excluded.baseline_ease_of_use,
  baseline_activity = excluded.baseline_activity,
  logo_url = excluded.logo_url,
  cover_image_url = excluded.cover_image_url,
  official_url = excluded.official_url,
  download_url = excluded.download_url,
  github_repo = excluded.github_repo,
  updated_at = timezone('utc'::text, now());

insert into public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, official_url, download_url, github_repo
) values (
  'provenance',
  'frontend',
  'Provenance',
  'Multi-system frontend on the iOS App Store supporting 30+ vintage consoles with automated boxart scraping and universal MFi controller support.',
  'Free & Open Source',
  'Active',
  ARRAY['iOS', 'iPadOS', 'tvOS'],
  true,
  'Basic',
  true,
  true,
  false,
  4,
  4,
  4,
  'https://avatars.githubusercontent.com/u/10419266?v=4',
  'https://opengraph.githubassets.com/1/Provenance-Emu/Provenance',
  'https://provenance-emu.com/',
  'https://apps.apple.com/us/app/provenance-video-game-emu/id6502844837',
  'Provenance-Emu/Provenance'
) on conflict (id) do update set
  name = excluded.name,
  short_desc = excluded.short_desc,
  pricing = excluded.pricing,
  status = excluded.status,
  supported_platforms = excluded.supported_platforms,
  has_built_in_scraper = excluded.has_built_in_scraper,
  theme_support = excluded.theme_support,
  touch_optimized = excluded.touch_optimized,
  gamepad_optimized = excluded.gamepad_optimized,
  can_replace_home_launcher = excluded.can_replace_home_launcher,
  baseline_adoption = excluded.baseline_adoption,
  baseline_ease_of_use = excluded.baseline_ease_of_use,
  baseline_activity = excluded.baseline_activity,
  logo_url = excluded.logo_url,
  cover_image_url = excluded.cover_image_url,
  official_url = excluded.official_url,
  download_url = excluded.download_url,
  github_repo = excluded.github_repo,
  updated_at = timezone('utc'::text, now());

insert into public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, official_url, download_url, github_repo
) values (
  'beacon-game-launcher',
  'frontend',
  'Beacon Game Launcher',
  'A modern, polished Android game & retro launcher designed for controllers and retro handhelds with automated scraping and clean layout views.',
  'Paid',
  'Active',
  ARRAY['Android'],
  true,
  'Rich',
  true,
  true,
  true,
  4,
  5,
  4,
  'https://play-lh.googleusercontent.com/9k3xoQaMinZqR19EHHU5ZkrfikV9NQWvg8U8tWpiFFKbobUE_JkVc24frgqCfsbVaebJGjKwU0l3UfnmJBJdyfk',
  'https://play-lh.googleusercontent.com/9k3xoQaMinZqR19EHHU5ZkrfikV9NQWvg8U8tWpiFFKbobUE_JkVc24frgqCfsbVaebJGjKwU0l3UfnmJBJdyfk',
  'https://play.google.com/store/apps/details?id=com.radikal.gamelauncher',
  'https://play.google.com/store/apps/details?id=com.radikal.gamelauncher',
  null
) on conflict (id) do update set
  name = excluded.name,
  short_desc = excluded.short_desc,
  pricing = excluded.pricing,
  status = excluded.status,
  supported_platforms = excluded.supported_platforms,
  has_built_in_scraper = excluded.has_built_in_scraper,
  theme_support = excluded.theme_support,
  touch_optimized = excluded.touch_optimized,
  gamepad_optimized = excluded.gamepad_optimized,
  can_replace_home_launcher = excluded.can_replace_home_launcher,
  baseline_adoption = excluded.baseline_adoption,
  baseline_ease_of_use = excluded.baseline_ease_of_use,
  baseline_activity = excluded.baseline_activity,
  logo_url = excluded.logo_url,
  cover_image_url = excluded.cover_image_url,
  official_url = excluded.official_url,
  download_url = excluded.download_url,
  github_repo = excluded.github_repo,
  updated_at = timezone('utc'::text, now());

insert into public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, official_url, download_url, github_repo
) values (
  'reset-collection',
  'frontend',
  'RESET Collection',
  'EmulationStation-style Android retro frontend featuring video snapshots, online scraping, and full gamepad navigation.',
  'Paid',
  'Active',
  ARRAY['Android'],
  true,
  'Rich',
  true,
  true,
  true,
  3,
  4,
  3,
  'https://play-lh.googleusercontent.com/LvprQY78MbQC8H8AAuR0C0mhp8ALl5OKWtwAh8GiGaz8vJEazzEoqughFyyqb9aoox58_QAGN2cEwXnKacwi6Iw',
  'https://play-lh.googleusercontent.com/LvprQY78MbQC8H8AAuR0C0mhp8ALl5OKWtwAh8GiGaz8vJEazzEoqughFyyqb9aoox58_QAGN2cEwXnKacwi6Iw',
  'https://play.google.com/store/apps/details?id=com.retroloungelab.resetcollection',
  'https://play.google.com/store/apps/details?id=com.retroloungelab.resetcollection',
  null
) on conflict (id) do update set
  name = excluded.name,
  short_desc = excluded.short_desc,
  pricing = excluded.pricing,
  status = excluded.status,
  supported_platforms = excluded.supported_platforms,
  has_built_in_scraper = excluded.has_built_in_scraper,
  theme_support = excluded.theme_support,
  touch_optimized = excluded.touch_optimized,
  gamepad_optimized = excluded.gamepad_optimized,
  can_replace_home_launcher = excluded.can_replace_home_launcher,
  baseline_adoption = excluded.baseline_adoption,
  baseline_ease_of_use = excluded.baseline_ease_of_use,
  baseline_activity = excluded.baseline_activity,
  logo_url = excluded.logo_url,
  cover_image_url = excluded.cover_image_url,
  official_url = excluded.official_url,
  download_url = excluded.download_url,
  github_repo = excluded.github_repo,
  updated_at = timezone('utc'::text, now());

insert into public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, official_url, download_url, github_repo
) values (
  'console-launcher',
  'frontend',
  'Console Launcher',
  'Transforms any Android phone, tablet, or retro handheld into a distraction-free console interface with controller-first navigation.',
  'Freemium',
  'Active',
  ARRAY['Android'],
  false,
  'Basic',
  true,
  true,
  true,
  3,
  4,
  4,
  'https://play-lh.googleusercontent.com/K3pS6ygUG3S5XwwQie3jNxpwdxQMBeA1K4OPEe6M9gdh55NKKbm8aWmBhpmEiB0KndCuUj39NYsZgiIsdUAW_A',
  'https://play-lh.googleusercontent.com/K3pS6ygUG3S5XwwQie3jNxpwdxQMBeA1K4OPEe6M9gdh55NKKbm8aWmBhpmEiB0KndCuUj39NYsZgiIsdUAW_A',
  'https://play.google.com/store/apps/details?id=com.k2.consolelauncher',
  'https://play.google.com/store/apps/details?id=com.k2.consolelauncher',
  null
) on conflict (id) do update set
  name = excluded.name,
  short_desc = excluded.short_desc,
  pricing = excluded.pricing,
  status = excluded.status,
  supported_platforms = excluded.supported_platforms,
  has_built_in_scraper = excluded.has_built_in_scraper,
  theme_support = excluded.theme_support,
  touch_optimized = excluded.touch_optimized,
  gamepad_optimized = excluded.gamepad_optimized,
  can_replace_home_launcher = excluded.can_replace_home_launcher,
  baseline_adoption = excluded.baseline_adoption,
  baseline_ease_of_use = excluded.baseline_ease_of_use,
  baseline_activity = excluded.baseline_activity,
  logo_url = excluded.logo_url,
  cover_image_url = excluded.cover_image_url,
  official_url = excluded.official_url,
  download_url = excluded.download_url,
  github_repo = excluded.github_repo,
  updated_at = timezone('utc'::text, now());

insert into public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, official_url, download_url, github_repo
) values (
  'ludihub',
  'frontend',
  'LudiHub',
  'Universal controller-first launcher for iOS and Android featuring deep-linking into Delta, RetroArch, and PPSSPP with SteamGridDB scraping.',
  'Freemium',
  'Active',
  ARRAY['iOS', 'iPadOS', 'Android'],
  true,
  'Rich',
  true,
  true,
  false,
  2,
  4,
  4,
  'https://ludihub.app/logo.png',
  'https://ludihub.app/logo.png',
  'https://ludihub.app/',
  'https://apps.apple.com/us/app/ludihub-gaming-launcher/id6475685516',
  null
) on conflict (id) do update set
  name = excluded.name,
  short_desc = excluded.short_desc,
  pricing = excluded.pricing,
  status = excluded.status,
  supported_platforms = excluded.supported_platforms,
  has_built_in_scraper = excluded.has_built_in_scraper,
  theme_support = excluded.theme_support,
  touch_optimized = excluded.touch_optimized,
  gamepad_optimized = excluded.gamepad_optimized,
  can_replace_home_launcher = excluded.can_replace_home_launcher,
  baseline_adoption = excluded.baseline_adoption,
  baseline_ease_of_use = excluded.baseline_ease_of_use,
  baseline_activity = excluded.baseline_activity,
  logo_url = excluded.logo_url,
  cover_image_url = excluded.cover_image_url,
  official_url = excluded.official_url,
  download_url = excluded.download_url,
  github_repo = excluded.github_repo,
  updated_at = timezone('utc'::text, now());

insert into public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, official_url, download_url, github_repo
) values (
  'lemuroid',
  'frontend',
  'Lemuroid',
  'Open-source all-in-one Libretro frontend for Android with Material You design, automatic ROM indexing, and cloud save sync.',
  'Free & Open Source',
  'Active',
  ARRAY['Android'],
  true,
  'Basic',
  true,
  true,
  false,
  4,
  5,
  4,
  'https://play-lh.googleusercontent.com/hWs9NKnx1bqRK3x8l-e2KlvBbgOBWikkdYsIvSVtkOHNNwLxpxv6OI6V2v2IaDpEantdC97JnEQdIYAEhA4fRw',
  'https://opengraph.githubassets.com/1/swordfish90/Lemuroid',
  'https://github.com/swordfish90/Lemuroid',
  'https://play.google.com/store/apps/details?id=com.swordfish.lemuroid',
  'swordfish90/Lemuroid'
) on conflict (id) do update set
  name = excluded.name,
  short_desc = excluded.short_desc,
  pricing = excluded.pricing,
  status = excluded.status,
  supported_platforms = excluded.supported_platforms,
  has_built_in_scraper = excluded.has_built_in_scraper,
  theme_support = excluded.theme_support,
  touch_optimized = excluded.touch_optimized,
  gamepad_optimized = excluded.gamepad_optimized,
  can_replace_home_launcher = excluded.can_replace_home_launcher,
  baseline_adoption = excluded.baseline_adoption,
  baseline_ease_of_use = excluded.baseline_ease_of_use,
  baseline_activity = excluded.baseline_activity,
  logo_url = excluded.logo_url,
  cover_image_url = excluded.cover_image_url,
  official_url = excluded.official_url,
  download_url = excluded.download_url,
  github_repo = excluded.github_repo,
  updated_at = timezone('utc'::text, now());

insert into public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, official_url, download_url, github_repo
) values (
  'arc-browser',
  'frontend',
  'Arc Browser',
  'Veteran arcade and retro emulator frontend built specifically for Android TV, Nvidia Shield, and controller-based Android handhelds.',
  'Paid',
  'Active',
  ARRAY['Android'],
  true,
  'Rich',
  true,
  true,
  true,
  3,
  3,
  3,
  'https://play-lh.googleusercontent.com/gdmHE6YFC3zTfLF5auAEdQok2SU-_1sbi-oKG4JylwfbKA5uH2IIW_8l9ZCm5zBWfeVYaIGjMcPM2xoooZzN',
  'https://play-lh.googleusercontent.com/gdmHE6YFC3zTfLF5auAEdQok2SU-_1sbi-oKG4JylwfbKA5uH2IIW_8l9ZCm5zBWfeVYaIGjMcPM2xoooZzN',
  'https://arcbrowser.com/',
  'https://play.google.com/store/apps/details?id=net.floatingpoint.android.arcturus',
  null
) on conflict (id) do update set
  name = excluded.name,
  short_desc = excluded.short_desc,
  pricing = excluded.pricing,
  status = excluded.status,
  supported_platforms = excluded.supported_platforms,
  has_built_in_scraper = excluded.has_built_in_scraper,
  theme_support = excluded.theme_support,
  touch_optimized = excluded.touch_optimized,
  gamepad_optimized = excluded.gamepad_optimized,
  can_replace_home_launcher = excluded.can_replace_home_launcher,
  baseline_adoption = excluded.baseline_adoption,
  baseline_ease_of_use = excluded.baseline_ease_of_use,
  baseline_activity = excluded.baseline_activity,
  logo_url = excluded.logo_url,
  cover_image_url = excluded.cover_image_url,
  official_url = excluded.official_url,
  download_url = excluded.download_url,
  github_repo = excluded.github_repo,
  updated_at = timezone('utc'::text, now());

insert into public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, official_url, download_url, github_repo
) values (
  'launchbox-for-android',
  'frontend',
  'LaunchBox for Android',
  'Android companion to the gold-standard PC frontend, featuring LaunchBox Games Database scraping, video themes, and direct emulator launching.',
  'Freemium',
  'Active',
  ARRAY['Android'],
  true,
  'Rich',
  true,
  true,
  true,
  3,
  3,
  3,
  'https://www.launchbox-app.com/apple-touch-icon.png',
  'https://www.launchbox-app.com/apple-touch-icon.png',
  'https://www.launchbox-app.com/android-about',
  'https://www.launchbox-app.com/android-download',
  null
) on conflict (id) do update set
  name = excluded.name,
  short_desc = excluded.short_desc,
  pricing = excluded.pricing,
  status = excluded.status,
  supported_platforms = excluded.supported_platforms,
  has_built_in_scraper = excluded.has_built_in_scraper,
  theme_support = excluded.theme_support,
  touch_optimized = excluded.touch_optimized,
  gamepad_optimized = excluded.gamepad_optimized,
  can_replace_home_launcher = excluded.can_replace_home_launcher,
  baseline_adoption = excluded.baseline_adoption,
  baseline_ease_of_use = excluded.baseline_ease_of_use,
  baseline_activity = excluded.baseline_activity,
  logo_url = excluded.logo_url,
  cover_image_url = excluded.cover_image_url,
  official_url = excluded.official_url,
  download_url = excluded.download_url,
  github_repo = excluded.github_repo,
  updated_at = timezone('utc'::text, now());

insert into public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, official_url, download_url, github_repo
) values (
  'dig-emulator-front-end',
  'frontend',
  'DIG - Emulator Front-End',
  'Classic, highly extensible Android frontend with auto ROM scanning, cover art scraper, voice search, and custom toolbar themes.',
  'Freemium',
  'Active',
  ARRAY['Android'],
  true,
  'Rich',
  true,
  true,
  true,
  3,
  3,
  2,
  'https://play-lh.googleusercontent.com/UnCIe555XVuB0UP_cPD5175_IwkYwZB7AKYzyo8mVDjhSbVKIcieVjGr4AqAQIgN5Q',
  'https://play-lh.googleusercontent.com/UnCIe555XVuB0UP_cPD5175_IwkYwZB7AKYzyo8mVDjhSbVKIcieVjGr4AqAQIgN5Q',
  'https://digdroid.com/',
  'https://digdroid.com/',
  null
) on conflict (id) do update set
  name = excluded.name,
  short_desc = excluded.short_desc,
  pricing = excluded.pricing,
  status = excluded.status,
  supported_platforms = excluded.supported_platforms,
  has_built_in_scraper = excluded.has_built_in_scraper,
  theme_support = excluded.theme_support,
  touch_optimized = excluded.touch_optimized,
  gamepad_optimized = excluded.gamepad_optimized,
  can_replace_home_launcher = excluded.can_replace_home_launcher,
  baseline_adoption = excluded.baseline_adoption,
  baseline_ease_of_use = excluded.baseline_ease_of_use,
  baseline_activity = excluded.baseline_activity,
  logo_url = excluded.logo_url,
  cover_image_url = excluded.cover_image_url,
  official_url = excluded.official_url,
  download_url = excluded.download_url,
  github_repo = excluded.github_repo,
  updated_at = timezone('utc'::text, now());