DELETE FROM public.items WHERE id = 'test';

INSERT INTO public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, screenshots, official_url, download_url, github_repo
) VALUES (
  'daijisho',
  'frontend',
  'Daijishō',
  '안드로이드 레트로 게임기를 위한 모던 오픈소스 런처. 내장 스크래퍼, 다양한 커뮤니티 테마, 홈 런처 대체 및 레트로어치브먼트 연동 지원.',
  'Free & Open Source',
  'Active',
  ARRAY['Android'],
  true,
  'Rich',
  true,
  true,
  true,
  5,
  4,
  4,
  'https://avatars.githubusercontent.com/u/130823084?v=4',
  'https://raw.githubusercontent.com/TapiocaFox/Daijishou/main/fastlane/metadata/android/en-US/images/featureGraphic.png',
  '{}',
  'https://github.com/TapiocaFox/Daijishou',
  'https://play.google.com/store/apps/details?id=com.tapiocafox.daijishou',
  'TapiocaFox/Daijishou'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  short_desc = EXCLUDED.short_desc,
  pricing = EXCLUDED.pricing,
  status = EXCLUDED.status,
  supported_platforms = EXCLUDED.supported_platforms,
  has_built_in_scraper = EXCLUDED.has_built_in_scraper,
  theme_support = EXCLUDED.theme_support,
  touch_optimized = EXCLUDED.touch_optimized,
  gamepad_optimized = EXCLUDED.gamepad_optimized,
  can_replace_home_launcher = EXCLUDED.can_replace_home_launcher,
  baseline_adoption = EXCLUDED.baseline_adoption,
  baseline_ease_of_use = EXCLUDED.baseline_ease_of_use,
  baseline_activity = EXCLUDED.baseline_activity,
  logo_url = EXCLUDED.logo_url,
  cover_image_url = EXCLUDED.cover_image_url,
  official_url = EXCLUDED.official_url,
  download_url = EXCLUDED.download_url,
  github_repo = EXCLUDED.github_repo,
  updated_at = timezone('utc'::text, now());

INSERT INTO public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, screenshots, official_url, download_url, github_repo
) VALUES (
  'retroarch',
  'frontend',
  'RetroArch',
  '에뮬레이션 생태계의 모듈형 통합 프론트엔드이자 코어 런처. 셰이더, 넷플레이, 내장 스크래퍼 및 전 플랫폼 지원.',
  'Free & Open Source',
  'Active',
  ARRAY['Android', 'iOS', 'Windows', 'Linux', 'macOS'],
  true,
  'Rich',
  true,
  true,
  false,
  5,
  2,
  5,
  'https://avatars.githubusercontent.com/u/7994464?v=4',
  'https://www.retroarch.com/images/banner.png',
  '{}',
  'https://www.retroarch.com/',
  'https://www.retroarch.com/?page=platforms',
  'libretro/RetroArch'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  short_desc = EXCLUDED.short_desc,
  pricing = EXCLUDED.pricing,
  status = EXCLUDED.status,
  supported_platforms = EXCLUDED.supported_platforms,
  has_built_in_scraper = EXCLUDED.has_built_in_scraper,
  theme_support = EXCLUDED.theme_support,
  touch_optimized = EXCLUDED.touch_optimized,
  gamepad_optimized = EXCLUDED.gamepad_optimized,
  can_replace_home_launcher = EXCLUDED.can_replace_home_launcher,
  baseline_adoption = EXCLUDED.baseline_adoption,
  baseline_ease_of_use = EXCLUDED.baseline_ease_of_use,
  baseline_activity = EXCLUDED.baseline_activity,
  logo_url = EXCLUDED.logo_url,
  cover_image_url = EXCLUDED.cover_image_url,
  official_url = EXCLUDED.official_url,
  download_url = EXCLUDED.download_url,
  github_repo = EXCLUDED.github_repo,
  updated_at = timezone('utc'::text, now());

INSERT INTO public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, screenshots, official_url, download_url, github_repo
) VALUES (
  'beacon-launcher',
  'frontend',
  'Beacon Game Launcher',
  '안드로이드 휴대용 기기와 컨트롤러에 최적화된 모던 유료 게임 런처. 빠른 자동 스크래핑과 군더더기 없는 미니멀 UI.',
  'Paid',
  'Active',
  ARRAY['Android'],
  true,
  'Rich',
  true,
  true,
  true,
  4,
  5,
  4,
  'https://play-lh.googleusercontent.com/9k3xoQaMinZqR19EHHU5ZkrfikV9NQWvg8U8tWpiFFKbobUE_JkVc24frgqCfsbVaebJGjKwU0l3UfnmJBJdyfk',
  null,
  '{}',
  'https://play.google.com/store/apps/details?id=com.radikal.gamelauncher',
  'https://play.google.com/store/apps/details?id=com.radikal.gamelauncher',
  null
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  short_desc = EXCLUDED.short_desc,
  pricing = EXCLUDED.pricing,
  status = EXCLUDED.status,
  supported_platforms = EXCLUDED.supported_platforms,
  has_built_in_scraper = EXCLUDED.has_built_in_scraper,
  theme_support = EXCLUDED.theme_support,
  touch_optimized = EXCLUDED.touch_optimized,
  gamepad_optimized = EXCLUDED.gamepad_optimized,
  can_replace_home_launcher = EXCLUDED.can_replace_home_launcher,
  baseline_adoption = EXCLUDED.baseline_adoption,
  baseline_ease_of_use = EXCLUDED.baseline_ease_of_use,
  baseline_activity = EXCLUDED.baseline_activity,
  logo_url = EXCLUDED.logo_url,
  cover_image_url = EXCLUDED.cover_image_url,
  official_url = EXCLUDED.official_url,
  download_url = EXCLUDED.download_url,
  github_repo = EXCLUDED.github_repo,
  updated_at = timezone('utc'::text, now());

INSERT INTO public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, screenshots, official_url, download_url, github_repo
) VALUES (
  'lemuroid',
  'frontend',
  'Lemuroid',
  'Material You 디자인 기반의 올인원 안드로이드 Libretro 에뮬레이터 겸 프론트엔드. 롬 폴더 지정 즉시 자동 인덱싱 및 클라우드 세이브 지원.',
  'Free & Open Source',
  'Active',
  ARRAY['Android'],
  true,
  'Basic',
  true,
  true,
  false,
  4,
  5,
  4,
  'https://play-lh.googleusercontent.com/hWs9NKnx1bqRK3x8l-e2KlvBbgOBWikkdYsIvSVtkOHNNwLxpxv6OI6V2v2IaDpEantdC97JnEQdIYAEhA4fRw',
  null,
  '{}',
  'https://github.com/swordfish90/Lemuroid',
  'https://play.google.com/store/apps/details?id=com.swordfish.lemuroid',
  'swordfish90/Lemuroid'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  short_desc = EXCLUDED.short_desc,
  pricing = EXCLUDED.pricing,
  status = EXCLUDED.status,
  supported_platforms = EXCLUDED.supported_platforms,
  has_built_in_scraper = EXCLUDED.has_built_in_scraper,
  theme_support = EXCLUDED.theme_support,
  touch_optimized = EXCLUDED.touch_optimized,
  gamepad_optimized = EXCLUDED.gamepad_optimized,
  can_replace_home_launcher = EXCLUDED.can_replace_home_launcher,
  baseline_adoption = EXCLUDED.baseline_adoption,
  baseline_ease_of_use = EXCLUDED.baseline_ease_of_use,
  baseline_activity = EXCLUDED.baseline_activity,
  logo_url = EXCLUDED.logo_url,
  cover_image_url = EXCLUDED.cover_image_url,
  official_url = EXCLUDED.official_url,
  download_url = EXCLUDED.download_url,
  github_repo = EXCLUDED.github_repo,
  updated_at = timezone('utc'::text, now());

INSERT INTO public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, screenshots, official_url, download_url, github_repo
) VALUES (
  'iisu',
  'frontend',
  'iiSU',
  '안드로이드 휴대용 기기를 위한 비주얼 중심의 차세대 에뮬레이션 프론트엔드. 닌텐도 3DS 감성의 듀얼 씬 인터페이스와 애니메이션 위젯 지원.',
  'Free',
  'Active',
  ARRAY['Android'],
  true,
  'Rich',
  true,
  true,
  true,
  3,
  3,
  4,
  'https://avatars.githubusercontent.com/u/235037752?v=4',
  null,
  '{}',
  'https://github.com/iisu-network/iiSU',
  'https://github.com/iisu-network/iiSU/releases',
  'iisu-network/iiSU'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  short_desc = EXCLUDED.short_desc,
  pricing = EXCLUDED.pricing,
  status = EXCLUDED.status,
  supported_platforms = EXCLUDED.supported_platforms,
  has_built_in_scraper = EXCLUDED.has_built_in_scraper,
  theme_support = EXCLUDED.theme_support,
  touch_optimized = EXCLUDED.touch_optimized,
  gamepad_optimized = EXCLUDED.gamepad_optimized,
  can_replace_home_launcher = EXCLUDED.can_replace_home_launcher,
  baseline_adoption = EXCLUDED.baseline_adoption,
  baseline_ease_of_use = EXCLUDED.baseline_ease_of_use,
  baseline_activity = EXCLUDED.baseline_activity,
  logo_url = EXCLUDED.logo_url,
  cover_image_url = EXCLUDED.cover_image_url,
  official_url = EXCLUDED.official_url,
  download_url = EXCLUDED.download_url,
  github_repo = EXCLUDED.github_repo,
  updated_at = timezone('utc'::text, now());

INSERT INTO public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, screenshots, official_url, download_url, github_repo
) VALUES (
  'neostation',
  'frontend',
  'NeoStation',
  '가볍고 직관적인 모던 에뮬레이션 프론트엔드. 기기 간 세이브 파일을 실시간 동기화하는 NeoSync, RetroAchievements 및 ScreenScraper 지원.',
  'Free & Open Source',
  'Active',
  ARRAY['Android', 'Windows'],
  true,
  'Rich',
  true,
  true,
  true,
  3,
  4,
  4,
  'https://neostation.dev/favicon.png',
  null,
  '{}',
  'https://neostation.dev/',
  'https://github.com/misobadev/neostation-frontend/releases',
  'misobadev/neostation-frontend'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  short_desc = EXCLUDED.short_desc,
  pricing = EXCLUDED.pricing,
  status = EXCLUDED.status,
  supported_platforms = EXCLUDED.supported_platforms,
  has_built_in_scraper = EXCLUDED.has_built_in_scraper,
  theme_support = EXCLUDED.theme_support,
  touch_optimized = EXCLUDED.touch_optimized,
  gamepad_optimized = EXCLUDED.gamepad_optimized,
  can_replace_home_launcher = EXCLUDED.can_replace_home_launcher,
  baseline_adoption = EXCLUDED.baseline_adoption,
  baseline_ease_of_use = EXCLUDED.baseline_ease_of_use,
  baseline_activity = EXCLUDED.baseline_activity,
  logo_url = EXCLUDED.logo_url,
  cover_image_url = EXCLUDED.cover_image_url,
  official_url = EXCLUDED.official_url,
  download_url = EXCLUDED.download_url,
  github_repo = EXCLUDED.github_repo,
  updated_at = timezone('utc'::text, now());

INSERT INTO public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, screenshots, official_url, download_url, github_repo
) VALUES (
  'cocoon',
  'frontend',
  'Cocoon',
  '안드로이드 휴대기기 및 듀얼 스크린에 특화된 커스텀 런처. 3DS 스타일 그리드/도크 UI, 디스코드 Rich Presence, RetroAchievements 및 위젯 지원.',
  'Free & Open Source',
  'Active',
  ARRAY['Android'],
  true,
  'Rich',
  true,
  true,
  true,
  3,
  4,
  4,
  'https://cocoon-shell.com/logo.svg',
  'https://cocoon-shell.com/images/news/3.0/banner.webp',
  '{}',
  'https://cocoon-shell.com/',
  'https://github.com/inssekt/CocoonFE/releases',
  'inssekt/CocoonFE'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  short_desc = EXCLUDED.short_desc,
  pricing = EXCLUDED.pricing,
  status = EXCLUDED.status,
  supported_platforms = EXCLUDED.supported_platforms,
  has_built_in_scraper = EXCLUDED.has_built_in_scraper,
  theme_support = EXCLUDED.theme_support,
  touch_optimized = EXCLUDED.touch_optimized,
  gamepad_optimized = EXCLUDED.gamepad_optimized,
  can_replace_home_launcher = EXCLUDED.can_replace_home_launcher,
  baseline_adoption = EXCLUDED.baseline_adoption,
  baseline_ease_of_use = EXCLUDED.baseline_ease_of_use,
  baseline_activity = EXCLUDED.baseline_activity,
  logo_url = EXCLUDED.logo_url,
  cover_image_url = EXCLUDED.cover_image_url,
  official_url = EXCLUDED.official_url,
  download_url = EXCLUDED.download_url,
  github_repo = EXCLUDED.github_repo,
  updated_at = timezone('utc'::text, now());

INSERT INTO public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, screenshots, official_url, download_url, github_repo
) VALUES (
  'launchbox',
  'frontend',
  'LaunchBox',
  'PC 및 안드로이드를 위한 프리미엄 게임 데이터베이스 런처. 화려한 Big Box 컨트롤러 UI, 커뮤니티 데이터베이스 스크래퍼 및 비디오 테마 지원.',
  'Freemium',
  'Active',
  ARRAY['Windows', 'Android'],
  true,
  'Rich',
  true,
  true,
  true,
  5,
  4,
  5,
  'https://www.launchbox-app.com/apple-touch-icon.png',
  null,
  '{}',
  'https://www.launchbox-app.com/',
  'https://www.launchbox-app.com/download',
  null
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  short_desc = EXCLUDED.short_desc,
  pricing = EXCLUDED.pricing,
  status = EXCLUDED.status,
  supported_platforms = EXCLUDED.supported_platforms,
  has_built_in_scraper = EXCLUDED.has_built_in_scraper,
  theme_support = EXCLUDED.theme_support,
  touch_optimized = EXCLUDED.touch_optimized,
  gamepad_optimized = EXCLUDED.gamepad_optimized,
  can_replace_home_launcher = EXCLUDED.can_replace_home_launcher,
  baseline_adoption = EXCLUDED.baseline_adoption,
  baseline_ease_of_use = EXCLUDED.baseline_ease_of_use,
  baseline_activity = EXCLUDED.baseline_activity,
  logo_url = EXCLUDED.logo_url,
  cover_image_url = EXCLUDED.cover_image_url,
  official_url = EXCLUDED.official_url,
  download_url = EXCLUDED.download_url,
  github_repo = EXCLUDED.github_repo,
  updated_at = timezone('utc'::text, now());

INSERT INTO public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, screenshots, official_url, download_url, github_repo
) VALUES (
  'retrobat',
  'frontend',
  'RetroBat',
  '윈도우 환경에서 EmulationStation과 RetroArch를 완벽 사전 구성해 제공하는 배포판. 별도 설정 없이 컨트롤러로 즉시 플레이 가능한 올인원 프론트엔드.',
  'Free & Open Source',
  'Active',
  ARRAY['Windows'],
  true,
  'Rich',
  false,
  true,
  false,
  4,
  5,
  4,
  'https://avatars.githubusercontent.com/u/57745778?v=4',
  null,
  '{}',
  'https://www.retrobat.org/',
  'https://www.retrobat.org/',
  'RetroBat-Team/retrobat-setup'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  short_desc = EXCLUDED.short_desc,
  pricing = EXCLUDED.pricing,
  status = EXCLUDED.status,
  supported_platforms = EXCLUDED.supported_platforms,
  has_built_in_scraper = EXCLUDED.has_built_in_scraper,
  theme_support = EXCLUDED.theme_support,
  touch_optimized = EXCLUDED.touch_optimized,
  gamepad_optimized = EXCLUDED.gamepad_optimized,
  can_replace_home_launcher = EXCLUDED.can_replace_home_launcher,
  baseline_adoption = EXCLUDED.baseline_adoption,
  baseline_ease_of_use = EXCLUDED.baseline_ease_of_use,
  baseline_activity = EXCLUDED.baseline_activity,
  logo_url = EXCLUDED.logo_url,
  cover_image_url = EXCLUDED.cover_image_url,
  official_url = EXCLUDED.official_url,
  download_url = EXCLUDED.download_url,
  github_repo = EXCLUDED.github_repo,
  updated_at = timezone('utc'::text, now());

INSERT INTO public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, screenshots, official_url, download_url, github_repo
) VALUES (
  'es-de',
  'frontend',
  'ES-DE',
  '멀티 플랫폼 컬렉션을 위한 완성형 에뮬레이션스테이션 프론트엔드. 독보적인 테마 커스터마이징, 내장 스크래퍼 및 전용 휴대기기/데스크톱 완벽 지원.',
  'Free & Open Source',
  'Active',
  ARRAY['Windows', 'Linux', 'macOS', 'Android'],
  true,
  'Rich',
  false,
  true,
  false,
  5,
  3,
  5,
  'https://gitlab.com/uploads/-/system/project/avatar/18817634/emulationstation_1024x1024.png?v=1789307732',
  null,
  '{}',
  'https://es-de.org/',
  'https://gitlab.com/es-de/emulationstation-de/-/releases',
  null
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  short_desc = EXCLUDED.short_desc,
  pricing = EXCLUDED.pricing,
  status = EXCLUDED.status,
  supported_platforms = EXCLUDED.supported_platforms,
  has_built_in_scraper = EXCLUDED.has_built_in_scraper,
  theme_support = EXCLUDED.theme_support,
  touch_optimized = EXCLUDED.touch_optimized,
  gamepad_optimized = EXCLUDED.gamepad_optimized,
  can_replace_home_launcher = EXCLUDED.can_replace_home_launcher,
  baseline_adoption = EXCLUDED.baseline_adoption,
  baseline_ease_of_use = EXCLUDED.baseline_ease_of_use,
  baseline_activity = EXCLUDED.baseline_activity,
  logo_url = EXCLUDED.logo_url,
  cover_image_url = EXCLUDED.cover_image_url,
  official_url = EXCLUDED.official_url,
  download_url = EXCLUDED.download_url,
  github_repo = EXCLUDED.github_repo,
  updated_at = timezone('utc'::text, now());

INSERT INTO public.items (
  id, type, name, short_desc, pricing, status,
  supported_platforms, has_built_in_scraper, theme_support, touch_optimized, gamepad_optimized, can_replace_home_launcher,
  baseline_adoption, baseline_ease_of_use, baseline_activity,
  logo_url, cover_image_url, screenshots, official_url, download_url, github_repo
) VALUES (
  'playnite',
  'frontend',
  'Playnite',
  'PC 및 에뮬레이션 라이브러리를 위한 강력한 오픈소스 게임 매니저 및 런처. Steam/Epic/GOG 자동 연동, TV 전체화면 모드, 방대한 플러그인 생태계 제공.',
  'Free & Open Source',
  'Active',
  ARRAY['Windows'],
  true,
  'Rich',
  false,
  true,
  false,
  5,
  4,
  5,
  'https://playnite.link/applogo.png',
  null,
  '{}',
  'https://playnite.link/',
  'https://playnite.link/',
  'JosefNemec/Playnite'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  short_desc = EXCLUDED.short_desc,
  pricing = EXCLUDED.pricing,
  status = EXCLUDED.status,
  supported_platforms = EXCLUDED.supported_platforms,
  has_built_in_scraper = EXCLUDED.has_built_in_scraper,
  theme_support = EXCLUDED.theme_support,
  touch_optimized = EXCLUDED.touch_optimized,
  gamepad_optimized = EXCLUDED.gamepad_optimized,
  can_replace_home_launcher = EXCLUDED.can_replace_home_launcher,
  baseline_adoption = EXCLUDED.baseline_adoption,
  baseline_ease_of_use = EXCLUDED.baseline_ease_of_use,
  baseline_activity = EXCLUDED.baseline_activity,
  logo_url = EXCLUDED.logo_url,
  cover_image_url = EXCLUDED.cover_image_url,
  official_url = EXCLUDED.official_url,
  download_url = EXCLUDED.download_url,
  github_repo = EXCLUDED.github_repo,
  updated_at = timezone('utc'::text, now());