// AUTO-GENERATED by scripts/fetchMetadata.mjs. DO NOT EDIT DIRECTLY.
// Update src/data/registry.js and run: npm run fetch-meta

import { FrontendItem, OSFirmwareItem } from '../types';

export const frontends: FrontendItem[] = [
  {
    "id": "daijisho",
    "name": "Daijishō",
    "shortDesc": "A retro launcher that manages your retro games libraries with built-in scraping, extensive theme support, and launcher replacement capability.",
    "pricing": "Free & Open Source",
    "status": "Active",
    "supportedPlatforms": [
      "Android"
    ],
    "hasBuiltInScraper": true,
    "themeSupport": "Rich",
    "touchOptimized": true,
    "gamepadOptimized": true,
    "canReplaceHomeLauncher": true,
    "logoUrl": "https://avatars.githubusercontent.com/u/130823084?v=4",
    "coverImageUrl": "https://opengraph.githubassets.com/1/TapiocaFox/Daijishou",
    "officialUrl": "https://github.com/TapiocaFox/Daijishou",
    "downloadUrl": "https://play.google.com/store/apps/details?id=com.tapiocafox.daijishou",
    "githubRepo": "TapiocaFox/Daijishou",
    "ratings": {
      "adoption": 5,
      "easeOfUse": 4,
      "activity": 4
    }
  },
  {
    "id": "es-de",
    "name": "ES-DE",
    "shortDesc": "The definitive frontend for browsing and launching games from your multi-platform collection with unrivaled theme customization.",
    "pricing": "Free & Open Source",
    "status": "Active",
    "supportedPlatforms": [
      "Android",
      "Linux",
      "Windows",
      "macOS"
    ],
    "hasBuiltInScraper": true,
    "themeSupport": "Rich",
    "touchOptimized": false,
    "gamepadOptimized": true,
    "canReplaceHomeLauncher": false,
    "logoUrl": "https://gitlab.com/uploads/-/system/project/avatar/18817634/emulationstation_1024x1024.png?v=1789307732",
    "coverImageUrl": "https://gitlab.com/uploads/-/system/project/avatar/18817634/emulationstation_1024x1024.png?v=1789307732",
    "officialUrl": "https://es-de.org/",
    "downloadUrl": "https://gitlab.com/es-de/emulationstation-de/-/releases",
    "ratings": {
      "adoption": 5,
      "easeOfUse": 3,
      "activity": 5
    }
  },
  {
    "id": "delta",
    "name": "Delta",
    "shortDesc": "The premier classic games frontend and emulator on the Apple App Store, supporting NES, SNES, N64, GBC, GBA, and DS with controller skins and boxart scraping.",
    "pricing": "Free & Open Source",
    "status": "Active",
    "supportedPlatforms": [
      "iOS",
      "iPadOS"
    ],
    "hasBuiltInScraper": true,
    "themeSupport": "Rich",
    "touchOptimized": true,
    "gamepadOptimized": true,
    "canReplaceHomeLauncher": false,
    "logoUrl": "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/ed/08/91/ed089193-2334-fd9b-752e-fc330791ee48/AppIcon-0-0-1x_U007epad-0-0-0-1-0-0-sRGB-85-220.png/512x512bb.jpg",
    "coverImageUrl": "https://opengraph.githubassets.com/1/rileytestut/Delta",
    "officialUrl": "https://deltaemulator.com/",
    "downloadUrl": "https://apps.apple.com/us/app/delta-game-emulator/id1048524688",
    "githubRepo": "rileytestut/Delta",
    "ratings": {
      "adoption": 5,
      "easeOfUse": 5,
      "activity": 4
    }
  },
  {
    "id": "retroarch",
    "name": "RetroArch",
    "shortDesc": "The foundational open-source multi-system frontend and modular engine, powering emulation, shaders, netplay, and game libraries on both App Store and Play Store.",
    "pricing": "Free & Open Source",
    "status": "Active",
    "supportedPlatforms": [
      "Android",
      "iOS",
      "Windows",
      "Linux",
      "macOS",
      "tvOS"
    ],
    "hasBuiltInScraper": true,
    "themeSupport": "Rich",
    "touchOptimized": true,
    "gamepadOptimized": true,
    "canReplaceHomeLauncher": false,
    "logoUrl": "https://avatars.githubusercontent.com/u/7994464?v=4",
    "coverImageUrl": "https://opengraph.githubassets.com/1/libretro/RetroArch",
    "officialUrl": "https://www.retroarch.com/",
    "downloadUrl": "https://apps.apple.com/us/app/retroarch/id6499539433",
    "githubRepo": "libretro/RetroArch",
    "ratings": {
      "adoption": 5,
      "easeOfUse": 2,
      "activity": 5
    }
  },
  {
    "id": "provenance",
    "name": "Provenance",
    "shortDesc": "Multi-system frontend on the iOS App Store supporting 30+ vintage consoles with automated boxart scraping and universal MFi controller support.",
    "pricing": "Free & Open Source",
    "status": "Active",
    "supportedPlatforms": [
      "iOS",
      "iPadOS",
      "tvOS"
    ],
    "hasBuiltInScraper": true,
    "themeSupport": "Basic",
    "touchOptimized": true,
    "gamepadOptimized": true,
    "canReplaceHomeLauncher": false,
    "logoUrl": "https://avatars.githubusercontent.com/u/10419266?v=4",
    "coverImageUrl": "https://opengraph.githubassets.com/1/Provenance-Emu/Provenance",
    "officialUrl": "https://provenance-emu.com/",
    "downloadUrl": "https://apps.apple.com/us/app/provenance-video-game-emu/id6502844837",
    "githubRepo": "Provenance-Emu/Provenance",
    "ratings": {
      "adoption": 4,
      "easeOfUse": 4,
      "activity": 4
    }
  },
  {
    "id": "beacon-game-launcher",
    "name": "Beacon Game Launcher",
    "shortDesc": "A modern, polished Android game & retro launcher designed for controllers and retro handhelds with automated scraping and clean layout views.",
    "pricing": "Paid",
    "status": "Active",
    "supportedPlatforms": [
      "Android"
    ],
    "hasBuiltInScraper": true,
    "themeSupport": "Rich",
    "touchOptimized": true,
    "gamepadOptimized": true,
    "canReplaceHomeLauncher": true,
    "logoUrl": "https://play-lh.googleusercontent.com/9k3xoQaMinZqR19EHHU5ZkrfikV9NQWvg8U8tWpiFFKbobUE_JkVc24frgqCfsbVaebJGjKwU0l3UfnmJBJdyfk",
    "coverImageUrl": "https://play-lh.googleusercontent.com/9k3xoQaMinZqR19EHHU5ZkrfikV9NQWvg8U8tWpiFFKbobUE_JkVc24frgqCfsbVaebJGjKwU0l3UfnmJBJdyfk",
    "officialUrl": "https://play.google.com/store/apps/details?id=com.radikal.gamelauncher",
    "downloadUrl": "https://play.google.com/store/apps/details?id=com.radikal.gamelauncher",
    "ratings": {
      "adoption": 4,
      "easeOfUse": 5,
      "activity": 4
    }
  },
  {
    "id": "reset-collection",
    "name": "RESET Collection",
    "shortDesc": "EmulationStation-style Android retro frontend featuring video snapshots, online scraping, and full gamepad navigation.",
    "pricing": "Paid",
    "status": "Active",
    "supportedPlatforms": [
      "Android"
    ],
    "hasBuiltInScraper": true,
    "themeSupport": "Rich",
    "touchOptimized": true,
    "gamepadOptimized": true,
    "canReplaceHomeLauncher": true,
    "logoUrl": "https://play-lh.googleusercontent.com/LvprQY78MbQC8H8AAuR0C0mhp8ALl5OKWtwAh8GiGaz8vJEazzEoqughFyyqb9aoox58_QAGN2cEwXnKacwi6Iw",
    "coverImageUrl": "https://play-lh.googleusercontent.com/LvprQY78MbQC8H8AAuR0C0mhp8ALl5OKWtwAh8GiGaz8vJEazzEoqughFyyqb9aoox58_QAGN2cEwXnKacwi6Iw",
    "officialUrl": "https://play.google.com/store/apps/details?id=com.retroloungelab.resetcollection",
    "downloadUrl": "https://play.google.com/store/apps/details?id=com.retroloungelab.resetcollection",
    "ratings": {
      "adoption": 3,
      "easeOfUse": 4,
      "activity": 3
    }
  },
  {
    "id": "console-launcher",
    "name": "Console Launcher",
    "shortDesc": "Transforms any Android phone, tablet, or retro handheld into a distraction-free console interface with controller-first navigation.",
    "pricing": "Freemium",
    "status": "Active",
    "supportedPlatforms": [
      "Android"
    ],
    "hasBuiltInScraper": false,
    "themeSupport": "Basic",
    "touchOptimized": true,
    "gamepadOptimized": true,
    "canReplaceHomeLauncher": true,
    "logoUrl": "https://play-lh.googleusercontent.com/K3pS6ygUG3S5XwwQie3jNxpwdxQMBeA1K4OPEe6M9gdh55NKKbm8aWmBhpmEiB0KndCuUj39NYsZgiIsdUAW_A",
    "coverImageUrl": "https://play-lh.googleusercontent.com/K3pS6ygUG3S5XwwQie3jNxpwdxQMBeA1K4OPEe6M9gdh55NKKbm8aWmBhpmEiB0KndCuUj39NYsZgiIsdUAW_A",
    "officialUrl": "https://play.google.com/store/apps/details?id=com.k2.consolelauncher",
    "downloadUrl": "https://play.google.com/store/apps/details?id=com.k2.consolelauncher",
    "ratings": {
      "adoption": 3,
      "easeOfUse": 4,
      "activity": 4
    }
  },
  {
    "id": "ludihub",
    "name": "LudiHub",
    "shortDesc": "Universal controller-first launcher for iOS and Android featuring deep-linking into Delta, RetroArch, and PPSSPP with SteamGridDB scraping.",
    "pricing": "Freemium",
    "status": "Active",
    "supportedPlatforms": [
      "iOS",
      "iPadOS",
      "Android"
    ],
    "hasBuiltInScraper": true,
    "themeSupport": "Rich",
    "touchOptimized": true,
    "gamepadOptimized": true,
    "canReplaceHomeLauncher": false,
    "logoUrl": "https://ludihub.app/logo.png",
    "coverImageUrl": "https://ludihub.app/logo.png",
    "officialUrl": "https://ludihub.app/",
    "downloadUrl": "https://apps.apple.com/us/app/ludihub-gaming-launcher/id6475685516",
    "ratings": {
      "adoption": 2,
      "easeOfUse": 4,
      "activity": 4
    }
  },
  {
    "id": "lemuroid",
    "name": "Lemuroid",
    "shortDesc": "Open-source all-in-one Libretro frontend for Android with Material You design, automatic ROM indexing, and cloud save sync.",
    "pricing": "Free & Open Source",
    "status": "Active",
    "supportedPlatforms": [
      "Android"
    ],
    "hasBuiltInScraper": true,
    "themeSupport": "Basic",
    "touchOptimized": true,
    "gamepadOptimized": true,
    "canReplaceHomeLauncher": false,
    "logoUrl": "https://play-lh.googleusercontent.com/hWs9NKnx1bqRK3x8l-e2KlvBbgOBWikkdYsIvSVtkOHNNwLxpxv6OI6V2v2IaDpEantdC97JnEQdIYAEhA4fRw",
    "coverImageUrl": "https://opengraph.githubassets.com/1/swordfish90/Lemuroid",
    "officialUrl": "https://github.com/swordfish90/Lemuroid",
    "downloadUrl": "https://play.google.com/store/apps/details?id=com.swordfish.lemuroid",
    "githubRepo": "swordfish90/Lemuroid",
    "ratings": {
      "adoption": 4,
      "easeOfUse": 5,
      "activity": 4
    }
  },
  {
    "id": "arc-browser",
    "name": "Arc Browser",
    "shortDesc": "Veteran arcade and retro emulator frontend built specifically for Android TV, Nvidia Shield, and controller-based Android handhelds.",
    "pricing": "Paid",
    "status": "Active",
    "supportedPlatforms": [
      "Android"
    ],
    "hasBuiltInScraper": true,
    "themeSupport": "Rich",
    "touchOptimized": true,
    "gamepadOptimized": true,
    "canReplaceHomeLauncher": true,
    "logoUrl": "https://play-lh.googleusercontent.com/gdmHE6YFC3zTfLF5auAEdQok2SU-_1sbi-oKG4JylwfbKA5uH2IIW_8l9ZCm5zBWfeVYaIGjMcPM2xoooZzN",
    "coverImageUrl": "https://play-lh.googleusercontent.com/gdmHE6YFC3zTfLF5auAEdQok2SU-_1sbi-oKG4JylwfbKA5uH2IIW_8l9ZCm5zBWfeVYaIGjMcPM2xoooZzN",
    "officialUrl": "https://arcbrowser.com/",
    "downloadUrl": "https://play.google.com/store/apps/details?id=net.floatingpoint.android.arcturus",
    "ratings": {
      "adoption": 3,
      "easeOfUse": 3,
      "activity": 3
    }
  },
  {
    "id": "launchbox-for-android",
    "name": "LaunchBox for Android",
    "shortDesc": "Android companion to the gold-standard PC frontend, featuring LaunchBox Games Database scraping, video themes, and direct emulator launching.",
    "pricing": "Freemium",
    "status": "Active",
    "supportedPlatforms": [
      "Android"
    ],
    "hasBuiltInScraper": true,
    "themeSupport": "Rich",
    "touchOptimized": true,
    "gamepadOptimized": true,
    "canReplaceHomeLauncher": true,
    "logoUrl": "https://www.launchbox-app.com/apple-touch-icon.png",
    "coverImageUrl": "https://www.launchbox-app.com/apple-touch-icon.png",
    "officialUrl": "https://www.launchbox-app.com/android-about",
    "downloadUrl": "https://www.launchbox-app.com/android-download",
    "ratings": {
      "adoption": 3,
      "easeOfUse": 3,
      "activity": 3
    }
  },
  {
    "id": "dig-emulator-front-end",
    "name": "DIG - Emulator Front-End",
    "shortDesc": "Classic, highly extensible Android frontend with auto ROM scanning, cover art scraper, voice search, and custom toolbar themes.",
    "pricing": "Freemium",
    "status": "Active",
    "supportedPlatforms": [
      "Android"
    ],
    "hasBuiltInScraper": true,
    "themeSupport": "Rich",
    "touchOptimized": true,
    "gamepadOptimized": true,
    "canReplaceHomeLauncher": true,
    "logoUrl": "https://play-lh.googleusercontent.com/UnCIe555XVuB0UP_cPD5175_IwkYwZB7AKYzyo8mVDjhSbVKIcieVjGr4AqAQIgN5Q",
    "coverImageUrl": "https://play-lh.googleusercontent.com/UnCIe555XVuB0UP_cPD5175_IwkYwZB7AKYzyo8mVDjhSbVKIcieVjGr4AqAQIgN5Q",
    "officialUrl": "https://digdroid.com/",
    "downloadUrl": "https://digdroid.com/",
    "ratings": {
      "adoption": 3,
      "easeOfUse": 3,
      "activity": 2
    }
  }
];

export const osFirmwares: OSFirmwareItem[] = [
  {
    "id": "atmosphere",
    "name": "Atmosphère",
    "shortDesc": "Atmosphère custom firmware system.",
    "pricing": "Free & Open Source",
    "status": "Active",
    "category": "First-Party",
    "targetDevices": [
      "Switch",
      "Switch OLED",
      "Switch Lite"
    ],
    "baseSystem": "Horizon OS Patch (Fusée / exosphère)",
    "exploitType": "Fusee-gelee / Modchip (HWFLY/Picofly)",
    "defaultFrontend": "Horizon Home Menu",
    "logoUrl": "https://avatars.githubusercontent.com/u/37918415?v=4",
    "coverImageUrl": "https://opengraph.githubassets.com/1/Atmosphere-NX/Atmosphere",
    "officialUrl": "https://github.com/Atmosphere-NX/Atmosphere",
    "downloadUrl": "https://github.com/Atmosphere-NX/Atmosphere",
    "githubRepo": "Atmosphere-NX/Atmosphere",
    "ratings": {
      "adoption": 5,
      "easeOfUse": 3,
      "activity": 5
    }
  },
  {
    "id": "freeboot-rgh",
    "name": "Freeboot / RGH",
    "shortDesc": "Custom NAND image and reset glitch hack (RGH) environment granting unrestricted execution on Xbox 360 hardware.",
    "pricing": "Free",
    "status": "Active",
    "category": "First-Party",
    "targetDevices": [
      "Xbox 360"
    ],
    "baseSystem": "Freeboot / Xenon Kernel Mod",
    "exploitType": "Modchip (RGH 1.2 / RGH 3.0)",
    "defaultFrontend": "Aurora",
    "logoUrl": "",
    "coverImageUrl": "",
    "officialUrl": "https://www.se7ensins.com/forums/forums/jtag-rgh.180/",
    "downloadUrl": "https://www.se7ensins.com/forums/forums/jtag-rgh.180/",
    "ratings": {
      "adoption": 5,
      "easeOfUse": 1,
      "activity": 3
    }
  },
  {
    "id": "knulli",
    "name": "Knulli",
    "shortDesc": "Knulli custom firmware system.",
    "pricing": "Free & Open Source",
    "status": "Active",
    "category": "Retro Handheld",
    "targetDevices": [
      "Anbernic RG35XX Plus",
      "RG35XX H",
      "RG40XX H",
      "TrimUI Smart Pro"
    ],
    "baseSystem": "Buildroot Linux (Batocera Fork)",
    "exploitType": "SD Boot",
    "defaultFrontend": "ES-DE",
    "logoUrl": "https://avatars.githubusercontent.com/u/166268572?v=4",
    "coverImageUrl": "https://opengraph.githubassets.com/1/knulli-cfw/distribution",
    "officialUrl": "https://github.com/knulli-cfw/distribution",
    "downloadUrl": "https://github.com/knulli-cfw/distribution",
    "githubRepo": "knulli-cfw/distribution",
    "ratings": {
      "adoption": 3,
      "easeOfUse": 4,
      "activity": 5
    }
  }
];

// Aliases for backwards compatibility
export const mockFrontends = frontends;
export const mockOSFirmwares = osFirmwares;
